variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CACHING_LAYER_TAG: $IMAGE_TAG-build_cache
  LATEST_TAG: $CI_REGISTRY_IMAGE:latest
  IMAGE_SHA_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  # Tell 'docker:dind' to enable TLS (recommended)
  # and generate certificates in the specified directory.
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://localhost:2375/

services:
  - docker:18.09.7-dind

before_script:
- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  image: docker:20.10
  script:
    - docker build -t $IMAGE_TAG -t $IMAGE_SHA_TAG -t $LATEST_TAG .
    - docker image push --all-tags $CI_REGISTRY_IMAGE